name: juan

on:
  schedule:
    - cron: '15 19 * * 0,1,2,4,5,6' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script # run main.py
        run: python src/main.py --email ${{ secrets.EMAIL_JRC }} --password ${{ secrets.PASS_JRC }} --booking-goals "{\"0\":{\"time\":\"1430\",\"name\":\"Método42\"},\"1\":{\"time\":\"1430\",\"name\":\"Método42\"},\"2\":{\"time\":\"1430\",\"name\":\"Método42\"},\"3\":{\"time\":\"1430\",\"name\":\"Método42\"},\"4\":{\"time\":\"1600\",\"name\":\"Método42\"}}" --box-name metodo42orsonwelles --box-id 10059 --days-in-advance 3 --booking-hour 2200
