name: juan_test

on:
  schedule:
    - cron: '50 13 * * 0,1,2,5,6' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python src/main.py --email ${{ secrets.EMAIL_JRC }} --password ${{ secrets.PASS_JRC }} --booking-goals "{\"3\":{\"time\":\"1750\",\"name\":\"Método42\"}}" --box-name metodo42orsonwelles --box-id 10059 --days-in-advance 2 --booking-hour 1600
